server:
  port: 8081

spring:
  application:
    name: payment-ms
  datasource:
    url: jdbc:postgresql://localhost:5432/paymentDB-ms
    username: postgres
    password: senh@BD
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        "globally_quoted_identifiers": "true"
      hibernate.format_sql: true
  cloud:
    function:
      definition: updatePayment
    stream:
      bindings:
        updatePayment-in-0:
          destination: send-communication-payment
          group: ${spring.application.name}
        updatePayment-out-0:
          destination: communication-payment-sent
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s

