spring:
  application:
    name: order-ms
  datasource:
    url: jdbc:postgresql://localhost:5432/ordersDB-ms
    username: postgres
    password: senh@BD
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        "globally_quoted_identifiers": "true"
      hibernate.format_sql: true

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
    function:
      definition: handlePaymentResult
    stream:
      bindings:
        requestPayment-out-0:
          destination: order-payment-requests
        handlePaymentResult-in-0:
          destination: payment-results
          group: ${spring.application.name}
          contentType: application/json
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

server:
  port: 0000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    #    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value} }
    prefer-ip-address: true

info:
  app:
    name: "order"
    description: "OrderFlow Order Application"
    version: "1.0.0"

logging:
  level:
    com:
      rtarcisio:
        orderms: debug
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000
